import './globals.css';
import { Inter } from 'next/font/google';
import TopBar from './topbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body className={`${inter.className} w-full flex items-center flex-col`}>
        <TopBar />
        {children}
      </body>
    </html>
  );
}
